name: Publish Module to PowerShell Gallery

on:
  push:
    
permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Publish Module to PowerShell Gallery
    runs-on: ubuntu-latest
    steps:
    - name: Publish Module to PowerShell Gallery
      uses: pcgeek86/publish-powershell-module-action@v20
      id: publish-module
      with:
        NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
